name: Invincible Space Dinosaur
favicon: null
layout_spectrum: 0.71454
typography_spectrum: 0.68564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e26a00'
    - '#d0d2d2'
    - '#666666'
    - '#000000'
    - '#fd0535'
  brandStrength: 0.375
  lightness: 0.22950652102008462
  saturation: 0
  rhythmicContrast: 0.8614756038878113
purpose: []
