name: Invincible Space Dinosaur
favicon: null
layout_spectrum: 0.9525
typography_spectrum: 0.9457657285965979
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfaf8'
    - '#16514b'
    - '#072114'
    - '#45c1c7'
    - '#a4f1e4'
  brandStrength: 0.06834146124310791
  lightness: 0.22950652102008462
  saturation: 0.7629504990763962
  rhythmicContrast: 0.8614756038878113
purpose: []
