name: Invincible Space Dinosaur
favicon: null
layout_spectrum: 0.9525
typography_spectrum: 0.68564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#06050b'
    - '#6f9580'
    - '#253650'
    - '#9a52a5'
  brandStrength: 0.6875
  lightness: 0.22950652102008462
  saturation: 0
  rhythmicContrast: 0.8614756038878113
purpose: []
